POST http://localhost:8080/api/v1/librarians/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsImxvZ2luIjoiYWRtaW4yIiwic3ViIjoiYWRtaW4yIiwiaWF0IjoxNzM0NzA3OTcyLCJleHAiOjE3MzUzMTI3NzJ9.4MDVbziuqTO5oktjUz4iHsC6AW83lGqpJURXZ45DzNU

{
  "name": "Oybek",
  "email": "ddiiyyoorrrr009@gmail.com",
  "username": "quyosh",
  "password": "12312312",
  "role": "ROLE_LIBRARIAN",
  "status": "ACTIVE"
}
